const json=(v,status=200)=>new Response(JSON.stringify(v),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const enc=s=>new TextEncoder().encode(s);
const b64url=bytes=>{let s='';for(const b of new Uint8Array(bytes))s+=String.fromCharCode(b);return btoa(s).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')};

const PAGE=`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#05070a"><title>Install Aftergraph for iPhone</title>
<style>:root{font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display",Inter,sans-serif;color:#f7f9fc;background:#05070a}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 50% 0,#182338 0,#090d14 34%,#05070a 70%);display:grid;place-items:center;padding:24px}main{width:min(720px,100%);padding:34px;border:1px solid #273244;border-radius:28px;background:rgba(10,14,21,.82);backdrop-filter:blur(18px);box-shadow:0 24px 80px rgba(0,0,0,.45)}.mark{width:68px;height:68px;border-radius:20px;display:grid;place-items:center;background:#f7f9fc;color:#05070a;font-size:36px;font-weight:800;margin-bottom:24px}h1{font-size:clamp(36px,8vw,62px);line-height:.98;margin:0 0 16px;letter-spacing:-.045em}p{color:#a9b6c8;font-size:18px;line-height:1.55}.state{display:inline-flex;gap:8px;align-items:center;margin:8px 0 14px;padding:8px 12px;border:1px solid #273244;border-radius:999px;color:#a9b6c8;font-size:13px}.dot{width:8px;height:8px;border-radius:50%;background:#ffbf69}button{width:100%;border:0;border-radius:17px;padding:17px 20px;font-size:18px;font-weight:700;background:#f7f9fc;color:#05070a;margin-top:12px;cursor:pointer}button:disabled{opacity:.45;cursor:not-allowed}.meta{margin-top:18px;padding-top:18px;border-top:1px solid #222d3c;font-size:14px;color:#7f8da0}.status{min-height:24px;margin-top:14px;color:#ccd5e1}.bad{color:#ff9c9c}.good{color:#9ff0bc}code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.9em}</style></head>
<body><main><div class="mark">A</div><h1>Aftergraph<br>for iPhone</h1><div class="state"><span class="dot"></span><span id="release-state">Checking release authority…</span></div><p>Native Aftergraph client distributed directly from Aftergraph using Apple's EU Web Distribution flow.</p><button id="install">Install Aftergraph</button><div id="status" class="status" aria-live="polite"></div><div class="meta">EU only. Native installation activates after Apple Web Distribution approval, notarization and an issued Alternative Distribution Package.</div></main>
<script>
const button=document.querySelector('#install'),status=document.querySelector('#status'),state=document.querySelector('#release-state');
function accountId(){let id=localStorage.getItem('aftergraph-install-account');if(!id){id=crypto.randomUUID();localStorage.setItem('aftergraph-install-account',id)}return id}
async function readiness(){try{const r=await fetch('/api/readiness',{cache:'no-store'}),d=await r.json();state.textContent=d.installable?'Verified release available':'Distribution staged — Apple release gate pending';document.querySelector('.dot').style.background=d.installable?'#65d68a':'#ffbf69'}catch{state.textContent='Unable to verify release state'}}
readiness();
button.addEventListener('click',async()=>{button.disabled=true;status.className='status';status.textContent='Preparing verified installation…';try{const r=await fetch('/api/install-link',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({account:accountId()})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Installation is not available yet.');status.className='status good';status.textContent='Opening Apple installation sheet…';location.href=d.installURL}catch(e){status.className='status bad';status.textContent=e.message;button.disabled=false}});
</script></body></html>`;

async function key(env){if(!env.ALT_DISTRIBUTION_PRIVATE_JWK)throw new Error('Apple distribution signing key is not configured');return crypto.subtle.importKey('jwk',JSON.parse(env.ALT_DISTRIBUTION_PRIVATE_JWK),{name:'ECDSA',namedCurve:'P-256'},false,['sign'])}
function configured(env){return env.WEB_DISTRIBUTION_ENABLED==='true'&&!!env.APPLE_ITEM_ID&&!!env.APPLE_VERSION_ID&&!!env.ALT_DISTRIBUTION_KEY_ID&&!!env.ALT_DISTRIBUTION_PRIVATE_JWK&&!!env.DISTRIBUTION_PACKAGE_URL}
async function token(env){const now=Math.floor(Date.now()/1000),header={alg:'ES256',kid:env.ALT_DISTRIBUTION_KEY_ID,typ:'JWT'},payload={iss:String(env.APPLE_ITEM_ID),iat:now,exp:now+1200,aud:'AppleDownloadVerification-v1',bid:env.BUNDLE_ID,dtype:'download',nonce:crypto.randomUUID(),iid:String(env.APPLE_ITEM_ID),vid:String(env.APPLE_VERSION_ID)};const unsigned=`${b64url(enc(JSON.stringify(header)))}.${b64url(enc(JSON.stringify(payload)))}`;const sig=await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},await key(env),enc(unsigned));return `${unsigned}.${b64url(sig)}`}
async function installLink(req,env){if(!configured(env))return json({error:'Aftergraph iOS is live, but native installation is not activated yet: Apple Web Distribution approval/notarization credentials are still required.'},503);const body=await req.json().catch(()=>({}));const account=String(body.account||crypto.randomUUID());const u=new URL('marketplace-kit://install');u.searchParams.set('alternativeDistributionPackage',env.DISTRIBUTION_PACKAGE_URL);u.searchParams.set('installVerificationToken',await token(env));u.searchParams.set('account',account);u.searchParams.set('appShareURL',env.APP_SHARE_URL);return json({installURL:u.toString()})}

export default{async fetch(req,env){const u=new URL(req.url),p=u.pathname;try{
if(p==='/'||p==='/install')return new Response(PAGE,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','content-security-policy':"default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'self'; img-src 'self' data:; base-uri 'none'; frame-ancestors 'none'",'strict-transport-security':'max-age=63072000; includeSubDomains; preload','x-content-type-options':'nosniff','referrer-policy':'no-referrer'}});
if(p==='/healthz')return json({status:'ok',service:'aftergraph-ios-web-distribution',version:'1.0.0'});
if(p==='/api/readiness')return json({installable:configured(env),bundleId:env.BUNDLE_ID||'org.aftergraph.ios',distribution:'apple-eu-web'});
if(p==='/api/install-link'&&req.method==='POST')return installLink(req,env);
if(p==='/.well-known/marketplace-kit'){const base=(env.PUBLIC_ORIGIN||'https://install.aftergraph.org').replace(/\/$/,'');return json({restore:`${base}/marketplace/restore`,updates:{url:`${base}/marketplace/updates`,pollingInterval:24},license:`${base}/marketplace/license`})}
if(p.startsWith('/marketplace/'))return json({error:'MarketplaceKit service staged; Apple-issued distribution assets are required before activation.'},503);
return new Response('Not found',{status:404});
}catch(e){return json({error:e instanceof Error?e.message:'internal error'},500)}}};