name = "aftergraph-site"
main = "worker.js"
compatibility_date = "2024-11-01"

[[kv_namespaces]]
binding = "AG_STATS"
id = "7b0696a1cd1b4656b9325589a3b6199c"

[build]
command = "node build-worker.cjs"
