/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        canvas: 'var(--ag-canvas)',
        'canvas-raised': 'var(--ag-canvas-raised)',
        surface: 'var(--ag-surface)',
        'surface-strong': 'var(--ag-surface-strong)',
        text: 'var(--ag-text)',
        'text-muted': 'var(--ag-text-muted)',
        'text-subtle': 'var(--ag-text-subtle)',
        border: 'var(--ag-border)',
        'border-strong': 'var(--ag-border-strong)',
        control: 'var(--ag-control)',
        'control-soft': 'var(--ag-control-soft)',
        evidence: 'var(--ag-evidence)',
        'evidence-soft': 'var(--ag-evidence-soft)',
        authority: 'var(--ag-authority)',
        'authority-soft': 'var(--ag-authority-soft)',
        decision: 'var(--ag-decision)',
        'decision-soft': 'var(--ag-decision-soft)',
        system: 'var(--ag-system)',
        'system-soft': 'var(--ag-system-soft)',
        danger: 'var(--ag-danger)',
        'danger-soft': 'var(--ag-danger-soft)',
      },
      fontFamily: {
        sans: ['var(--ag-font-interface)'],
        mono: ['var(--ag-font-code)'],
        serif: ['var(--ag-font-editorial)'],
      },
      borderRadius: {
        control: 'var(--ag-radius-control)',
        button: 'var(--ag-radius-button)',
        card: 'var(--ag-radius-card)',
        surface: 'var(--ag-radius-surface)',
        sheet: 'var(--ag-radius-sheet)',
        pill: 'var(--ag-radius-pill)',
      },
      spacing: {
        'ag-xxs': 'var(--ag-space-xxs)',
        'ag-xs': 'var(--ag-space-xs)',
        'ag-sm': 'var(--ag-space-sm)',
        'ag-md': 'var(--ag-space-md)',
        'ag-base': 'var(--ag-space-base)',
        'ag-lg': 'var(--ag-space-lg)',
        'ag-xl': 'var(--ag-space-xl)',
        'ag-2xl': 'var(--ag-space-xxl)',
        'ag-3xl': 'var(--ag-space-3xl)',
        'ag-4xl': 'var(--ag-space-4xl)',
        'ag-5xl': 'var(--ag-space-5xl)',
      },
    },
  },
  plugins: [],
}
